/** Centralized remote public assets */
export const publicAssets = {
  concreteNormal:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603359/suburbia-skateboard/concrete-normal.avif",
  metalNormal:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603411/suburbia-skateboard/metal-normal.avif",
  gripTapeRoughness:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603412/suburbia-skateboard/griptape-roughness.webp",
  gripTapeDiffuse:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603409/suburbia-skateboard/griptape-diffuse.webp",
  imageTexture:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603362/suburbia-skateboard/image-texture.png",
  bgTexture:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603360/suburbia-skateboard/bg-texture.webp",
  videoMask:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603358/suburbia-skateboard/video-mask.png",
  hdr: {
    warehouseHdri:
      "https://res.cloudinary.com/dng1meo0n/raw/upload/v1785673971/suburbia-skateboard/hdr/warehouse-hdri.hdr",
    warehouse512:
      "https://res.cloudinary.com/dng1meo0n/raw/upload/v1785673966/suburbia-skateboard/hdr/warehouse-512.hdr",
    warehouse256:
      "https://res.cloudinary.com/dng1meo0n/raw/upload/v1785673962/suburbia-skateboard/hdr/warehouse-256.hdr",
  },
  deck: {
    deckAgainstTheTide:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602821/suburbia-skateboard/deck/deck-against-the-tide.png",
    deckBlackYellow:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602821/suburbia-skateboard/deck/deck-black-yellow.png",
    deckDefault:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603254/suburbia-skateboard/deck/deck-default.webp",
    deckGrayBlack:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602821/suburbia-skateboard/deck/deck-gray-black.png",
    deckGreenNavy:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602821/suburbia-skateboard/deck/deck-green-navy.png",
    deckGridStreaks:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602822/suburbia-skateboard/deck/deck-grid-streaks.png",
    deckOniMask:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602822/suburbia-skateboard/deck/deck-oni-mask.png",
    deckPinkSwirl:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602821/suburbia-skateboard/deck/deck-pink-swirl.png",
    deckRedBlack:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602821/suburbia-skateboard/deck/deck-red-black.png",
    deckRedWhite:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602822/suburbia-skateboard/deck/deck-red-white.png",
    deckThankYou:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602822/suburbia-skateboard/deck/deck-thank-you.png",
    deckYellowBlack:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602822/suburbia-skateboard/deck/deck-yellow-black.png",
  },
  wheel: {
    wheelBlack:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602864/suburbia-skateboard/wheel/wheel-yellow.png",
    wheelBlue:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602862/suburbia-skateboard/wheel/wheel-blue.png",
    wheelCream:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602863/suburbia-skateboard/wheel/wheel-cream.png",
    wheelGreen:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602863/suburbia-skateboard/wheel/wheel-green.png",
    wheelNavy:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602863/suburbia-skateboard/wheel/wheel-navy.png",
    wheelPink:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602864/suburbia-skateboard/wheel/wheel-pink.png",
    wheelPurple:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602864/suburbia-skateboard/wheel/wheel-purple.png",
    wheelRed:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602864/suburbia-skateboard/wheel/wheel-red.png",
    wheelYellow:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785602864/suburbia-skateboard/wheel/wheel-yellow.png",
  },
  complete: {
    completeBlackYellow:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603918/suburbia-skateboard/complete/complete-black-yellow.png",
    completeGrayBlack:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603917/suburbia-skateboard/complete/complete-gray-black.png",
    completeGreenNavy:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603920/suburbia-skateboard/complete/complete-green-navy.png",
    completeGridStreaks:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603907/suburbia-skateboard/complete/complete-grid-streaks.png",
    completeOniMask:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603914/suburbia-skateboard/complete/complete-onimask.png",
    completePinkDrop:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603905/suburbia-skateboard/complete/complete-pink-drop.png",
    completeRedBlack:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603922/suburbia-skateboard/complete/complete-red-black.png",
    completeRedWhite:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603913/suburbia-skateboard/complete/complete-red-white.png",
    completeThankYou:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603911/suburbia-skateboard/complete/complete-thank-you.png",
    completeYellowBlack:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603909/suburbia-skateboard/complete/complete-yellow-black.png",
  },
  bgPaint:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785688229/suburbia-skateboard/bg-paint.png",
  person1:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785688219/suburbia-skateboard/person-1.png",
  person2:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785688217/suburbia-skateboard/person-2.png",
  person3:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785688220/suburbia-skateboard/person-3.png",
  person4:
    "https://res.cloudinary.com/dng1meo0n/image/upload/v1785688217/suburbia-skateboard/person-4.png",
  team: {
    carterBack:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603148/suburbia-skateboard/team/team-carter-back.png",
    carterFront:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603147/suburbia-skateboard/team/team-carter-front.png",
    dylanBack:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603146/suburbia-skateboard/team/team-dylan-back.png",
    dylanFront:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603143/suburbia-skateboard/team/team-dylan-front.png",
    jordanBack:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603142/suburbia-skateboard/team/team-jordan-back.png",
    jordanFront:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603146/suburbia-skateboard/team/team-jordan-front.png",
    sophieBack:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603144/suburbia-skateboard/team/team-sophie-back.png",
    sophieFront:
      "https://res.cloudinary.com/dng1meo0n/image/upload/v1785603145/suburbia-skateboard/team/team-sophie-front.png",
  },
} as const;
